# This is a basic workflow to help you get started with Actions

name: NodeJS Jest Unit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.0'
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: '4'
      
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
          cache: 'npm'
          
      - run: npm install
      #copy secrey key to config folder
      - run: touch letterOfRecGenerator/config/jwtRS256.key
      - run: echo "${{secret.SECRETKEY}}" >> letterOfRecGenerator/config/jwtRS256.key
      - run: cd letterOfRecGenerator && npm test
